version: '3.4'
services:
  db:
    container_name: ${PROJECT_PREFIX}-db
    image: mariadb:10.7.1-focal
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: feedback
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ${STORAGE_PATH}/mariadb:/var/lib/mysql
      - ${DB_MIGRATION_PATH}/paradise_schema.sql:/docker-entrypoint-initdb.d/migrate1.sql
