version: '3.4'
services:
  ss13-app:
    container_name: ${PROJECT_PREFIX}-app
    entrypoint: DreamDaemon paradise.dmb -port ${INNER_PORT} -trusted -close -verbose
    build:
      context: ../../
      args:
        - BYOND_MAJOR=${BYOND_MAJOR}
        - BYOND_MINOR=${BYOND_MINOR}
        - RUSTG=${RUSTG}
        - NODEJS=${NODEJS}
    ports:
      - ${OUTER_PORT}:${INNER_PORT}
    volumes:
      - ${STORAGE_PATH}/data:/station/data
